name: 'Phonito Security Docker Scan'
description: 'Scan Docker image for security vulnerabilities'
inputs:
  image:  # image and tag to scan
    description: 'Image and tag of Docker image to scan, e.g. my-app:latest'
    required: true
  phonito-token:  # image and tag to scan
    description: 'Token for your Phonito Security account. Get a token from: https://phonito.io/setup-ci'
    required: true
runs:
  using: 'node12'
  main: 'lib/index.js'
